### ISSUE TITLE
Installation macOS 13.0

### ISSUE THREAD

**Issue by taoning** [stephanwaz/raytraverse#1]
I have the following problem installing raytraverse on macOS 13
I ran 
```
pip install --upgrade pip setuptools wheel
pip install raytraverse
```
I also ran the following but got the same result
```
pip install git+https://github.com/stephanwaz/raytraverse
```

This is the terminal output:
```
Collecting git+https://github.com/stephanwaz/raytraverse
  Cloning https://github.com/stephanwaz/raytraverse to /private/var/folders/_w/6pnmllhd1xl0d9x4z_f79wtw0000gn/T/pip-req-build-ecgnaaj_
  Resolved https://github.com/stephanwaz/raytraverse to commit cd063835ecbe072f748e27b668f25b311403ce76
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from raytraverse==1.3.7) (1.8.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from raytraverse==1.3.7) (1.22.3)
Collecting skyfield
  Using cached skyfield-1.45-py3-none-any.whl (442 kB)
Collecting clasp
  Using cached clasp-1.1.8-py2.py3-none-any.whl (27 kB)
Collecting sklearn
  Using cached sklearn-0.0-py2.py3-none-any.whl
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from raytraverse==1.3.7) (3.5.1)
Collecting craytraverse>=0.1.5
  Using cached craytraverse-0.1.5.tar.gz (1.2 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting shapely
  Using cached Shapely-1.8.5.post1-cp310-cp310-macosx_11_0_arm64.whl (1.1 MB)
Collecting pybind11
  Using cached pybind11-2.10.0-py3-none-any.whl (213 kB)
Collecting sphinx-click
  Using cached sphinx_click-4.3.0-py3-none-any.whl (8.9 kB)
Requirement already satisfied: docutils in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from clasp->raytraverse==1.3.7) (0.16)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting configparser
  Using cached configparser-5.3.0-py3-none-any.whl (19 kB)
Requirement already satisfied: sphinx in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from clasp->raytraverse==1.3.7) (4.5.0)
Requirement already satisfied: click in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from clasp->raytraverse==1.3.7) (8.1.3)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->raytraverse==1.3.7) (4.31.2)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->raytraverse==1.3.7) (21.3)
Requirement already satisfied: pillow>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->raytraverse==1.3.7) (9.1.0)
Requirement already satisfied: pyparsing>=2.2.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->raytraverse==1.3.7) (3.0.7)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->raytraverse==1.3.7) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->raytraverse==1.3.7) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->raytraverse==1.3.7) (0.11.0)
Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sklearn->raytraverse==1.3.7) (1.1.2)
Collecting jplephem>=2.13
  Using cached jplephem-2.18-py3-none-any.whl (46 kB)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from skyfield->raytraverse==1.3.7) (2022.9.24)
Collecting sgp4>=2.2
  Using cached sgp4-2.21-cp310-cp310-macosx_11_0_arm64.whl (155 kB)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib->raytraverse==1.3.7) (1.16.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn->sklearn->raytraverse==1.3.7) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from scikit-learn->sklearn->raytraverse==1.3.7) (1.1.0)
Requirement already satisfied: babel>=1.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (2.9.1)
Requirement already satisfied: sphinxcontrib-qthelp in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (1.0.3)
Requirement already satisfied: imagesize in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (1.3.0)
Requirement already satisfied: sphinxcontrib-jsmath in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (1.0.1)
Requirement already satisfied: requests>=2.5.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (2.27.1)
Requirement already satisfied: Jinja2>=2.3 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (3.1.1)
Requirement already satisfied: sphinxcontrib-applehelp in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (1.0.2)
Requirement already satisfied: Pygments>=2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (2.11.2)
Requirement already satisfied: alabaster<0.8,>=0.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (0.7.12)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (1.1.5)
Requirement already satisfied: snowballstemmer>=1.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (2.2.0)
Requirement already satisfied: sphinxcontrib-devhelp in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from sphinx->clasp->raytraverse==1.3.7) (1.0.2)
Requirement already satisfied: pytz>=2015.7 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from babel>=1.3->sphinx->clasp->raytraverse==1.3.7) (2022.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from Jinja2>=2.3->sphinx->clasp->raytraverse==1.3.7) (2.1.1)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.5.0->sphinx->clasp->raytraverse==1.3.7) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.5.0->sphinx->clasp->raytraverse==1.3.7) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from requests>=2.5.0->sphinx->clasp->raytraverse==1.3.7) (3.3)
Building wheels for collected packages: raytraverse, craytraverse
  Building wheel for raytraverse (pyproject.toml): started
  Building wheel for raytraverse (pyproject.toml): finished with status 'done'
  Created wheel for raytraverse: filename=raytraverse-1.3.7-py3-none-any.whl size=1245737 sha256=c542d8856a86c5cc5a5a978657fb8b805ea262a1dd3f4d242e303443cfb24da2
  Stored in directory: /private/var/folders/_w/6pnmllhd1xl0d9x4z_f79wtw0000gn/T/pip-ephem-wheel-cache-37qynrmu/wheels/ee/ad/e5/a69e6458c1060347cdc3a67de0b45aac77ee7933a34e6973d6
  Building wheel for craytraverse (pyproject.toml): started
  Building wheel for craytraverse (pyproject.toml): finished with status 'error'
Successfully built raytraverse
Failed to build craytraverse
 for craytraverse (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
        File "/private/var/folders/_w/6pnmllhd1xl0d9x4z_f79wtw0000gn/T/pip-build-env-dv4ltdt0/overlay/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 613, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/private/var/folders/_w/6pnmllhd1xl0d9x4z_f79wtw0000gn/T/pip-build-env-dv4ltdt0/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 141, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/private/var/folders/_w/6pnmllhd1xl0d9x4z_f79wtw0000gn/T/pip-build-env-dv4ltdt0/overlay/lib/python3.10/site-packages/skbuild/cmaker.py", line 95, in get_cmake_version
          raise SKBuildError(
      Traceback (most recent call last):
      
      Problem with the CMake installation, aborting build. CMake executable is /private/var/folders/_w/6pnmllhd1xl0d9x4z_f79wtw0000gn/T/pip-build-env-dv4ltdt0/overlay/lib/python3.10/site-packages/cmake/data/CMake.app/Contents/bin/cmake
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for craytraverse
ERROR: Could not build wheels for craytraverse, which is required to install pyproject.toml-based projects
```
The error was followed by a pop-up:
<img width="372" alt="Screenshot 2022-10-27 at 2 22 31 PM" src="https://user-images.githubusercontent.com/7775623/198400818-96e8905f-94c9-4f91-8220-ea08cb4f300e.png">

I verified that `cmake` works on my command-line.

**Comment by taoning** [comment]
The problem went after upgrading to macOS 13.1.
